[package]
name = "bitdex-primitives"
version = "2.0.0-rc6"
authors = ["pangwa <pangwa@gmail.com>"]
edition = "2018"


[dependencies.sp-core]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-rc6'

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-core/std",
]