[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    "primitives",
    'runtime',
    'modules/cloverdex',
    'modules/evm-accounts',
    'modules/evm-bridge',
    'modules/reward-pool',
    'modules/incentives',
    'modules/traits',
]

[patch.crates-io]
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = "b7712fed2c58a898f7706e16861d7109c8f585a5" }
