[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    "primitives",
    'runtime',
    'modules/bithumbdex',
    'modules/reward-pool',
    'modules/incentives',
    'modules/traits',
]
