[package]
name = "bitdex-rpc"
version = "2.0.0-rc6"
authors = ["pangwa <pangwa@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Runtime API definition required by System RPC extensions."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
sp-runtime = { version = "2.0.0-rc6" }
sp-api = { version = "2.0.0-rc6" }
sp-blockchain = { version = "2.0.0-rc6" }
bitdex-rpc-runtime-api = { path = "runtime-api" }

[features]
default = ["std"]
std = [
  "bitdex-rpc-runtime-api/std",
	"sp-api/std",
	"codec/std",
]