[package]
authors = ['pangwa <pangwa@gmail.com>']
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'bitdex-runtime'
repository = 'https://github.com/pangwa/bitdex/'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
bithumbdex = { path = "../modules/bithumbdex", default-features = false }

[dependencies.bitdex-rpc-runtime-api]
default-features = false
version = '2.0.0-rc6'
package = 'bitdex-rpc-runtime-api'
path = '../rpc/runtime-api'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.frame-executive]
default-features = false
version = '2.0.0-rc6'

[dependencies.frame-support]
default-features = false
version = '2.0.0-rc6'

[dependencies.frame-system]
default-features = false
version = '2.0.0-rc6'

[dependencies.frame-system-rpc-runtime-api]
default-features = false
version = '2.0.0-rc6'

[dependencies.orml-currencies]
default-features = false
git = 'https://github.com/open-web3-stack/open-runtime-module-library.git'
rev = '12c5cdc297'

[dependencies.orml-tokens]
default-features = false
git = 'https://github.com/open-web3-stack/open-runtime-module-library.git'
rev = '12c5cdc297'

[dependencies.orml-traits]
default-features = false
git = 'https://github.com/open-web3-stack/open-runtime-module-library.git'
rev = '12c5cdc297'

[dependencies.pallet-authorship]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-babe]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-balances]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-collective]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-grandpa]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-indices]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-staking]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-session]
default-features = false
features = ["historical"]
version = '2.0.0-rc6'

[dependencies.pallet-randomness-collective-flip]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-staking-reward-curve]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-sudo]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-timestamp]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-transaction-payment]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-transaction-payment-rpc-runtime-api]
default-features = false
version = '2.0.0-rc6'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.sp-api]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-block-builder]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-consensus-babe]
default-features = false
version = '0.8.0-rc6'

[dependencies.sp-core]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-inherents]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-offchain]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-session]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-staking]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-transaction-pool]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-version]
default-features = false
version = '2.0.0-rc6'

[dependencies.primitives]
  default-features = false
  package = 'bitdex-primitives'
  path = '../primitives'
  version = '2.0.0-rc6'

[dependencies.pallet-democracy]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-elections-phragmen]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-treasury]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-membership]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-scheduler]
default-features = false
version = '2.0.0-rc6'

[features]
default = ['std']
std = [
    'bitdex-rpc-runtime-api/std',
    'bithumbdex/std',
    'codec/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'orml-currencies/std',
    'orml-tokens/std',
    'orml-traits/std',
    'pallet-authorship/std',
    'pallet-babe/std',
    'pallet-balances/std',
    "pallet-collective/std",
    'pallet-grandpa/std',
    'pallet-indices/std',
    'pallet-staking/std',
    'pallet-session/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-staking/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'primitives/std',
    "pallet-democracy/std",
    "pallet-elections-phragmen/std",
    "pallet-treasury/std",
    "pallet-membership/std",
    "pallet-scheduler/std",
]

[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.5'
