[package]
name = 'clover'
authors = ['Clover Network <https://github.com/clover-network>']
build = 'build.rs'
description = 'Clover node'
edition = '2018'
license = 'GPL-3.0'
homepage = 'https://cloverdefi.com'
repository = 'https://github.com/clover-network/clover'
version = '0.9.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'clover'

[dependencies]
primitives = { package = 'clover-primitives', path = '../primitives', version = '0.9.0'}
clover-runtime = {path = '../runtime', version = '0.9.0' }
clover-rpc = {default-features = false, version = '0.9.0', package = 'clover-rpc', path = '../rpc' }

jsonrpc-core = '15.0.0'
jsonrpc-pubsub = "15.0.0"
structopt = '0.3.8'
serde_json = "1.0"

pallet-contracts = { version = "2.0.0", default-features = false }
pallet-contracts-rpc = { version = "0.8.0" }
pallet-transaction-payment-rpc = { version = '2.0.0' }
sc-basic-authorship = { version = '0.8.0' }
sc-cli = { version = "0.8.0" }
sc-client-api = { version = '2.0.0' }
sc-consensus = { version = '0.8.0' }
sc-consensus-babe = { version = '0.8.0' }
sc-consensus-babe-rpc = { version = '0.8.0' }
sc-consensus-epochs = { version = "0.8.0" }
sc-finality-grandpa-rpc = { version = "0.8.0" }
sc-finality-grandpa = { version = '0.8.0' }
sc-executor = {features = ['wasmtime'], version = '0.8.0' }
sc-keystore = { version = "2.0.0" }
sc-network = { version = '0.8.0' }
sc-rpc = { version = '2.0.0' }
sc-rpc-api = { version = '0.8.0' }
sc-service = { features = ['wasmtime'], version = "0.8.0" }
sc-transaction-pool = { version = '2.0.0' }
sp-api = { version = '2.0.0' }
sp-block-builder = { version = '2.0.0' }
sp-blockchain = { version = '2.0.0' }
sp-consensus = { version = '0.8.0' }
sp-consensus-babe = { version = '0.8.0' }
sp-core = { version = '2.0.0' }
sp-finality-grandpa = { version = '2.0.0' }
sp-inherents = { version = '2.0.0' }
sp-runtime = { version = '2.0.0' }
sp-transaction-pool = { version = '2.0.0' }
substrate-frame-rpc-system = { version = '2.0.0' }
hex-literal = { version = '0.3.1' }
sc-telemetry = { version = '2.0.0' }
clover-evm = { path = "../modules/clover-evm" }
clover-ethereum = { path = "../modules/clover-ethereum" }
fc-rpc = { path = "../rpc/client/rpc" }
fp-rpc = { path = "../primitives/rpc" }
fc-consensus = { path = "../rpc/client/consensus" }
primitive-types = { version = "0.7.0", default-features = false, features = ["rlp", "byteorder"] }

[build-dependencies.substrate-build-script-utils]
version = '2.0.0'
