[package]
name = 'clover'
authors = ['Clover Network <https://github.com/clover-network>']
build = 'build.rs'
description = 'Clover node'
edition = '2018'
license = 'GPL-3.0'
homepage = 'https://cloverdefi.com'
repository = 'https://github.com/clover-network/clover'
version = '0.9.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'clover'

[dependencies.clover-runtime]
path = '../runtime'
version = '0.9.0'

[dependencies.clover-rpc]
default-features = false
version = '0.9.0'
package = 'clover-rpc'
path = '../rpc'

[dependencies.pallet-transaction-payment-rpc]
version = '2.0.0-rc6'

[dependencies.sc-basic-authorship]
version = '0.8.0-rc6'

[dependencies.sc-cli]
features = ['wasmtime']
version = '0.8.0-rc6'

[dependencies.sc-client-api]
version = '2.0.0-rc6'

[dependencies.sc-consensus]
version = '0.8.0-rc6'

[dependencies.sc-consensus-babe]
version = '0.8.0-rc6'

[dependencies.sc-consensus-babe-rpc]
version = '0.8.0-rc6'

[dependencies.sc-executor]
features = ['wasmtime']
version = '0.8.0-rc6'

[dependencies.sc-finality-grandpa]
version = '0.8.0-rc6'

[dependencies.sc-network]
version = '0.8.0-rc6'

[dependencies.sc-rpc]
version = '2.0.0-rc6'

[dependencies.sc-rpc-api]
version = '0.8.0-rc6'

[dependencies.sc-service]
features = ['wasmtime']
version = '0.8.0-rc6'

[dependencies.sc-transaction-pool]
version = '2.0.0-rc6'

[dependencies.sp-api]
version = '2.0.0-rc6'

[dependencies.sp-block-builder]
version = '2.0.0-rc6'

[dependencies.sp-blockchain]
version = '2.0.0-rc6'

[dependencies.sp-consensus]
version = '0.8.0-rc6'

[dependencies.sp-consensus-babe]
version = '0.8.0-rc6'

[dependencies.sp-core]
version = '2.0.0-rc6'

[dependencies.sp-finality-grandpa]
version = '2.0.0-rc6'

[dependencies.sp-inherents]
version = '2.0.0-rc6'

[dependencies.sp-runtime]
version = '2.0.0-rc6'

[dependencies.sp-transaction-pool]
version = '2.0.0-rc6'

[dependencies.substrate-frame-rpc-system]
version = '2.0.0-rc6'

[dependencies.primitives]
  package = 'clover-primitives'
  path = '../primitives'
  version = '0.9.0'

[dependencies]
jsonrpc-core = '14.0.3'
jsonrpc-pubsub = "14.2.0"
structopt = '0.3.8'
sc-consensus-epochs = { version = "0.8.0-rc6" }
sc-keystore = { version = "2.0.0-rc6" }
sc-finality-grandpa-rpc = { version = "0.8.0-rc6" }
serde_json = "1.0"

[build-dependencies.substrate-build-script-utils]
version = '2.0.0-rc6'
